version: "3"
services:
  kaggle:
    build: .
    runtime: nvidia
    container_name: g2net2022
    volumes:
      - $PWD:/tmp/working
      - /home/hiroshi_yoshihara/data_disk_1/kaggle/g2net-detecting-continuous-gravitational-waves/:/home/hiroshi_yoshihara/data_disk_1/kaggle/g2net-detecting-continuous-gravitational-waves/
    working_dir: /tmp/working
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0  --port=8888  --allow-root --LabApp.token='g2net'